{% set python_min = "3.11" %}
{% set name = "bagofholding" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bagofholding-{{ version }}.tar.gz
  sha256: f66a80d20b0f6b788d0163c1158775f16b5a66dcc5989de45acfc48525b0c47b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - bidict
    - h5py
    - hatchling ==1.27.0
    - hatch-vcs ==0.5.0
    - numpy
    - pygtrie
    - pyiron_snippets
    - pip
  run:
    - python >={{ python_min }},<3.15
    - bidict ==0.23.1
    - h5py >=3.12.1,<3.15.0
    - numpy >=1.26.4,<2.4.0
    - pygtrie >=2.5.0,<2.6.0
    - pyiron_snippets >=1.0.0,<2.0.0

test:
  imports:
    - bagofholding
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/bagofholding
  summary: bagofholding - browsable, partially-reloadable serialization for pickleable python objects.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - liamhuber
    - niklassiemer
